### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by xiroV** [Tiggles/Github-Gameoff-2019#3]
Current idea: Sky (blue gradient) with clouds.

Could change depending on the level, i.e.

 - Lv 1: Ground level, houses, etc. Maybe country side.
 - Lv 2: Larger city, ground level? Maybe on roofs, or something.
 - Lv n-1: Sky with clouds,
 - Lv n: Space?

**Comment by Ezbob** [comment]
pogo rally race

**Comment by Tiggles** [comment]
?

**Comment by Ezbob** [comment]
I just thought a race field would be a cool idea for some bonus stuff.
